export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SHOW_LOADER = 'SHOW_LOADER';
export const SET_USER = 'SET_USER';
export const SET_MESSAGE = 'SET_MESSAGE';
