exports.data = [[
{ name: 'berniesanders', change: -55 },
{ name: 'megynkelly', change: 110 },
{ name: 'demnagvasalia', change: 66 },
{ name: 'Roxannegay', change: 10 },
{ name: 'Marina abramovich', change: -55 },
{ name: 'megynkelly', change: 110 },
{ name: 'andreessen horowitz', change: 10 },
{ name: 'ElonMusk', change: 66 },
{ name: 'vitalik buterin', change: 50 },
{ name: 'Camille paglia', change: 10 }
],
[
{ name: 'Jeffree star', change: -44 },
{ name: 'Alicia Garza', change: -44 },
{ name: 'Keith ellison', change: 99 },
{ name: 'pamanderson', change: 88 },
{ name: 'chelseahandler', change: 20 },
{ name: 'ta nehisi coates', change: -10 },
{ name: 'Cat marnell', change: -44 },
{ name: 'lilyrosedepp', change: 99 },
{ name: 'Rachel maddow', change: 88 },
{ name: 'chelseahandler', change: 20 },
],
[
{ name: 'EdwardSnowden', change: -7.2 },
{ name: 'Hari nef', change: -7.2 },
{ name: 'Daniel Kaluuya', change: 99 },
{ name: 'Maria charapova', change: 6 },
{ name: 'Kanye west', change: -110 },
{ name: 'Gwyneth paltrow', change: 200 },
{ name: 'Mikecernovich', change: -7.2 },
{ name: 'Terry Gross', change: 99 },
{ name: 'khloekardashian', change: 6 },
{ name: 'parishilton', change: -10 }
],
];
