# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'Relevant' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Relevant
  pod 'Firebase/Core'
  pod 'TwitterKit'

  target 'relevantNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'relevantNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for relevantNative
  pod 'Firebase/Core'
  pod 'TwitterKit'


  pod 'react-native-wkwebview', :path => '../node_modules/react-native-wkwebview-reborn'

end
