export const ADD_COMMUNITY = 'ADD_COMMUNITY';
export const SET_COMMUNITIES = 'SET_COMMUNITIES';
export const UPDATE_COMMUNITY = 'UPDATE_COMMUNITY';
export const REMOVE_COMMUNITY = 'REMOVE_COMMUNITY';
export const ADD_USER_MEMBERSHIP = 'ADD_USER_MEMBERSHIP';
export const SET_USER_MEMBERSHIPS = 'SET_USER_MEMBERSHIPS';

// careful this one sets active community in admin reducer
export const SET_COMMUNITY = 'SET_COMMUNITY';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SHOW_LOADER = 'SHOW_LOADER';
export const SET_COMMUNITY_MEMBERS = 'SET_COMMUNITY_MEMBERS';

export const SET_USER_SEARCH = 'SET_USER_SEARCH';
export const SET_USER = 'SET_USER';
export const SET_USERS = 'SET_USERS';
export const SET_CONTACTS = 'SET_CONTACTS';
export const SET_USER_INDEX = 'SET_USER_INDEX';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_AUTH_USER = 'UPDATE_AUTH_USER';
export const SET_STATS = 'SET_STATS';
export const ADD_STATS = 'ADD_STATS';
export const SET_SELECTED_USER_DATA = 'SET_SELECTED_USER_DATA';
export const SET_TWITTER = 'SET_TWITTER';
export const SET_LOADING = 'SET_LOADING';

export const SET_ACTIVE_POST = 'SET_ACTIVE_POST';
export const SET_RECENT_POSTS = 'SET_RECENT_POSTS';
export const OPEN_INVEST = 'OPEN_INVEST';
export const CLOSE_INVEST = 'CLOSE_INVEST';
export const SET_NOTIF = 'SET_NOTIF';
export const SET_FEED = 'SET_FEED';
export const SET_POSTS_BY_RANK = 'SET_POSTS_BY_RANK';
export const UPDATE_FEED = 'UPDATE_FEED';
export const UPDATE_EARNINGS = 'UPDATE_EARNINGS';
export const LOADING_POST_INVESTMENTS = 'LOADING_POST_INVESTMENTS';
export const LOADING_INVESTMENTS = 'LOADING_INVESTMENTS';
export const SET_POST_INVESTMENTS = 'SET_POST_INVESTMENTS';
export const UPDATE_POST_INVESTMENTS = 'UPDATE_POST_INVESTMENTS';
export const UNDO_POST_INVESTMENT = 'UNDO_POST_INVESTMENT';
export const SET_INVESTMENTS = 'SET_INVESTMENTS';

export const CLEAR_POSTS = 'CLEAR_POSTS';
export const UPDATE_POSTS = 'UPDATE_POSTS';
export const ADD_POST = 'ADD_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const SET_POSTS = 'SET_POSTS';
export const POST_ERROR = 'POST_ERROR';
export const POST_SUCCESS = 'POST_SUCCESS';
export const SET_MESSAGES = 'SET_MESSAGES';
export const REMOVE_POST = 'REMOVE_POST';
export const SET_POSTS_SIMPLE = 'SET_POSTS_SIMPLE';
export const UPDATE_POSTS_INVEST = 'UPDATE_POSTS_INVEST';
export const UNDO_POSTS_INVEST = 'UNDO_POSTS_INVEST';
export const INC_FEED_COUNT = 'INC_FEED_COUNT';
export const SET_FEED_COUNT = 'SET_FEED_COUNT';
export const SET_TOP_POSTS = 'SET_TOP_POSTS';
export const SET_RELATED = 'SET_RELATED';
export const SET_USER_POSTS = 'SET_USER_POSTS';

export const SET_SUBSCRIPTIONS = 'SET_SUBSCRIPTIONS';

export const DESELECT_TAG = 'DESELECT_TAG';
export const SELECT_TAG = 'SELECT_TAG';
export const SET_PARENT_TAGS = 'SET_PARENT_TAGS';
export const SET_DISCOVER_TAGS = 'SET_DISCOVER_TAGS';
export const UPDATE_PARENT_TAG = 'UPDATE_PARENT_TAG';

export const SET_ACTIVITY = 'SET_ACTIVITY';
export const SET_COUNT = 'SET_COUNT';
export const ADD_UNREAD_ACTIVITIES = 'ADD_UNREAD_ACTIVITIES';

export const SET_ANIMATION = 'SET_ANIMATION';
export const CLEAR_ANIMATION = 'CLEAR_ANIMATION';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ARCHIVE_COMMENTS = 'ARCHIVE_COMMENTS';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const SET_COMMENTS = 'SET_COMMENTS';

export const SET_GENERAL_ACTIVITY = 'SET_GENERAL_ACTIVITY';
export const ADD_GENERAL_ACTIVITY = 'ADD_GENERAL_ACTIVITY';
export const SET_AUTH_STATUS_TEXT = 'SET_AUTH_STATUS_TEXT';
export const GET_POSTS = 'GET_POSTS';
export const REFRESH_POSTS = 'REFRESH_POSTS';

export const SET_CREATE_POST_STATE = 'SET_CREATE_POST_STATE';
export const SET_POST_CATEGORY = 'SET_POST_CATEGORY';
export const CLEAR_CREATE_POST = 'CLEAR_CREATE_POST';
export const SET_TOPIC_POSTS = 'SET_TOPIC_POSTS';

export const REFRESH_ROUTE = 'REFRESH_ROUTE';
export const RELOAD_ROUTE = 'RELOAD_ROUTE';
export const RELOAD_ALL_TABS = 'RELOAD_ALL_TABS';
export const SHOW_TOOLTIP = 'SHOW_TOOLTIP';
export const TOOLTIP_READY = 'TOOLTIP_READY';
export const SET_TOOLTIP_DATA = 'SET_TOOLTIP_DATA';
export const TOGGLE_TOPICS = 'TOGGLE_TOPICS';
export const SCROLL = 'SCROLL';
export const SET_ONBOARDING_STEP = 'SET_ONBOARDING_STEP';
export const SET_BUTTON_TOOLTIP = 'SET_BUTTON_TOOLTIP';
export const REGISTER_GESTURE = 'REGISTER_GESTURE';

export const SET_INVITE_COUNT = 'SET_INVITE_COUNT';
export const SET_INVITES = 'SET_INVITES';
export const UPDATE_INVITE = 'UPDATE_INVITE';
export const DESTROY_INVITE = 'DESTROY_INVITE';
export const SET_WAITLIST = 'SET_WAITLIST';
export const SET_DOWNVOTES = 'SET_DOWNVOTES';
export const DELETE_WAITLIST_USER = 'DELETE_WAITLIST_USER';
export const SET_INVITE_CODE = 'SET_INVITE_CODE';

export const SET_ERROR = 'SET_ERROR';

export const SET_EARNINGS = 'SET_EARNINGS';
export const ADD_EARNING = 'ADD_EARNING';
export const UPDATE_EARNING = 'UPDATE_EARNING';
export const REMOVE_EARNING = 'REMOVE_EARNING';

export const CASH_OUT = {
  REQUEST: 'CASH_OUT_REQUEST',
  SUCCESS: 'CASH_OUT_SUCCESS',
  FAILURE: 'CASH_OUT_FAILURE'
};

export const CONNECT_ACCOUNT = {
  REQUEST: 'CONNECT_ACCOUNT_REQUEST',
  SUCCESS: 'CONNECT_ACCOUNT_SUCCESS',
  FAILURE: 'CONNECT_ACCOUNT_FAILURE'
};

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const SHOW_BANNER_PROMPT = 'SHOW_BANNER_PROMPT';
export const HIDE_BANNER_PROMPT = 'HIDE_BANNER_PROMPT';

export const SET_SCROLL_TAB = 'SET_SCROLL_TAB';
export const OPEN_WEB_SIDE_NAV = 'OPEN_WEB_SIDE_NAV';
export const CLOSE_WEB_SIDE_NAV = 'CLOSE_WEB_SIDE_NAV';
export const LOCK_DRAWER = 'LOCK_DRAWER';
export const SET_WIDTH = 'SET_WIDTH';
